<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Scanner\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Sender\Tools\wirehair-encode.mjs" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Scanner\libs\wirehair-wasm\dist\wirehair.mjs" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Scanner\libs\wirehair-wasm\dist\wirehair_core.mjs" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
